Update 03_riferimenti-sigle.rst
italia/lg-modellointeroperabilita-docs pull request #196
Opened 2021-02-08 16:41 UTC by mfortini

Fix di alcuni numeri. NB **da controllare eventuali riferimenti "rotti"**

2021-02-08 20:28 UTC, vintra73 commented
@mfortini volevo segnalarti che la convenzione per referenziare gli atti UE è <anno>/<numero>vedi ad esempio https://eur-lex.europa.eu/legal-content/IT/TXT/?uri=celex%3A32016R0679

2021-02-08 20:42 UTC, mfortini commented
Ok grazie, allora come non detto. Però in alcuni punti era EU 2016/1024 e poi nella spiegazione citata come "risoluzione 1024/2016", non mi sembrava coerente

2021-02-08 21:07 UTC, vintra73 commented
@mfortini hai assolutamente ragione sulla coerenza... io uniformerei a  anno/numero

2021-02-10 15:12 UTC, ioggstream requested changes
Fix EU notation pls.

2021-02-11 17:03 UTC, mfortini reviewed
Ho ricercato i vari documenti e allineato anno/numero o numero/anno a seconda di quello che c'è scritto nel doc originale

2021-02-11 19:03 UTC, vintra73 commented
@ioggstream per me ok

2021-02-11 19:20 UTC, merged