Update 05_progettazione-dei-servizi-digitali.rst
italia/lg-modellointeroperabilita-docs pull request #224
Opened 2021-02-11 08:58 UTC by ggentili

introdotto un richiamo al CAD su servizi digitali e distinzione dagli e-service

2021-02-16 18:02 UTC, vintra73 requested changes
@ioggstream @ggentili ho messo alcune mie riflessioni sulle modifiche proposte

2021-02-16 18:17 UTC, ggentili commented on doc/00_Linee guida interoperabilità tecnica/05_progettazione-dei-servizi-digitali.rst
> +and Communication Technology (ICT) sfruttando anche la modalità digitale.
volevo dire che attraverso l'ICT il servizio può cos' offrire anche la modalità digitale. E' l'art.64-bis al comma 1-quater che dice "anche in modalità digitale". cmq non è molto rilevante, se sta scritto prima

2021-02-16 19:15 UTC, vintra73 approved these changes

2021-02-16 19:15 UTC, vintra73 commented
@ioggstream per me ok

2021-02-19 16:24 UTC, vintra73 commented
@ioggstream per me ok

2021-02-25 13:39 UTC, ioggstream commented on doc/00_Linee guida interoperabilità tecnica/05_progettazione-dei-servizi-digitali.rst
>  ==================================
```suggestion
Progettazione dei servizi digitali e degli e-service
=====================================
```

2021-02-25 13:43 UTC, ioggstream commented on doc/00_Linee guida interoperabilità tecnica/05_progettazione-dei-servizi-digitali.rst
> +and Communication Technology (ICT) sfruttando anche la modalità digitale.
```suggestion
and Communication Technology (ICT) in coerenza col principio "digital first".
```

2021-02-25 13:44 UTC, ioggstream commented on doc/00_Linee guida interoperabilità tecnica/05_progettazione-dei-servizi-digitali.rst
> +fruitori. Gli e-service sono una particolare categoria di servizi in rete basati su interfacce applicative (API).
```suggestion
fruitori.
Gli e-service sono una particolare categoria di servizi in rete basati su interfacce applicative (API).
```

2021-02-25 13:45 UTC, ioggstream commented on doc/00_Linee guida interoperabilità tecnica/05_progettazione-dei-servizi-digitali.rst
>  ==================================
```suggestion
Progettazione dei servizi digitali e degli e-service
=======================================
```

2021-02-25 13:46 UTC, ioggstream commented on doc/00_Linee guida interoperabilità tecnica/05_progettazione-dei-servizi-digitali.rst
> +=====================================
```suggestion
==========================================================
```

2021-02-25 13:50 UTC, merged